name: build
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ant-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'     # cambia si usas otro JDK

      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build with Ant (NetBeans)
        working-directory: Proyecto_SistemaContable   # << aquí le dices en qué carpeta está build.xml
        run: ant -noinput clean jar
